In [1]:
# load the numpy library into your Python environment
import numpy as np

# Question 1:

a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
# Use intersect to get the common values between two arrays

print(np.intersect1d(a, b))

[2 4]


In [15]:
# Question 2:

# Create 5X3 array
# create a array range of 15 elements

np.arange(1, 16). reshape(5, 3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [19]:
# Question 3:


from collections import Counter

import numpy as np

a = np.array([12, 5, 7, 15, 3, 1, 8])
b = np.array([14, 6, 3, 11, 19, 12, 5])

# Used counter to remove the common elements between tow arrays

ca = Counter(a)
cb = Counter(b)

a_a = sorted((ca - cb).elements())
b_b = sorted((cb - ca).elements())

print(a_a)
print(b_b)

[1, 7, 8, 15]
[6, 11, 14, 19]


In [20]:
# Question 5:

import pandas
import numpy as np

# supress scientific notation
np.set_printoptions(suppress = True)

# read the data file from GitHub and convert to a NumPy ndarray object
nyc_water = pandas.read_csv('https://raw.githubusercontent.com/jtopor/DAV-5400/master/Week4/Water_Consumption_In_The_New_York_City.csv').values

# verify you have an ndarray object
type(nyc_water)

numpy.ndarray

In [21]:
# Question 5A:

# Used indexing to find the column valume of new york city water consumption

nyc_water[:, 2]


array([1512. , 1506. , 1309. , 1382. , 1424. , 1465. , 1326. , 1351. ,
       1447. , 1484. , 1402. , 1424. , 1469. , 1369. , 1368.5, 1357.7,
       1325.7, 1297.9, 1205.5, 1219.5, 1237.2, 1240.4, 1184. , 1135.6,
       1093.7, 1099.5, 1138. , 1069. , 1114. , 1098. , 1007.5, 1039. ,
       1021. , 1009.1, 1006.1,  996. , 1009. , 1002. ,  990.2])

In [23]:
# Create a new array called water_consum with third column values

water_consum = ([1512. , 1506. , 1309. , 1382. , 1424. , 1465. , 1326. , 1351. ,
       1447. , 1484. , 1402. , 1424. , 1469. , 1369. , 1368.5, 1357.7,
       1325.7, 1297.9, 1205.5, 1219.5, 1237.2, 1240.4, 1184. , 1135.6,
       1093.7, 1099.5, 1138. , 1069. , 1114. , 1098. , 1007.5, 1039. ,
       1021. , 1009.1, 1006.1,  996. , 1009. , 1002. ,  990.2])
# used max function to find the maxium value of water_consum
np.max(water_consum)

1512.0

In [24]:
# Question 5B:

# Used indexing to find the column value of year 

nyc_water[:,0]

array([1979., 1980., 1981., 1982., 1983., 1984., 1985., 1986., 1987.,
       1988., 1989., 1990., 1991., 1992., 1993., 1994., 1995., 1996.,
       1997., 1998., 1999., 2000., 2001., 2002., 2003., 2004., 2005.,
       2006., 2007., 2008., 2009., 2010., 2011., 2012., 2013., 2014.,
       2015., 2016., 2017.])

In [25]:
# Create a new array called calen_year with first column values 
calen_year = ([1979., 1980., 1981., 1982., 1983., 1984., 1985., 1986., 1987.,
       1988., 1989., 1990., 1991., 1992., 1993., 1994., 1995., 1996.,
       1997., 1998., 1999., 2000., 2001., 2002., 2003., 2004., 2005.,
       2006., 2007., 2008., 2009., 2010., 2011., 2012., 2013., 2014.,
       2015., 2016., 2017.])

# used shape to find out the total number of calender year 
np.shape(calen_year)

(39,)

In [4]:
 import pandas
import numpy as np

# supress scientific notation
np.set_printoptions(suppress = True)

# read the data file from GitHub and convert to a NumPy ndarray object
nyc_water = pandas.read_csv('https://raw.githubusercontent.com/jtopor/DAV-5400/master/Week4/Water_Consumption_In_The_New_York_City.csv').values

# verify you have an ndarray object
type(nyc_water)

numpy.ndarray

In [5]:
# Question 5C:

# Used indexing to find the column value of per capita water consumption 


nyc_water[:,3]


array([213., 213., 185., 194., 198., 203., 182., 185., 197., 202., 191.,
       194., 199., 184., 182., 179., 174., 169., 155., 155., 156., 155.,
       148., 141., 136., 136., 141., 132., 137., 135., 123., 127., 123.,
       121., 119., 118., 118., 117., 115.])

In [7]:

per_cap_daily_consum = ([213., 213., 185., 194., 198., 203., 182., 185., 197., 202., 191.,
       194., 199., 184., 182., 179., 174., 169., 155., 155., 156., 155.,
       148., 141., 136., 136., 141., 132., 137., 135., 123., 127., 123.,
       121., 119., 118., 118., 117., 115.])
# used mean fuction to find the mean of the per capita daily water consumption in nyc
np.mean(per_cap_daily_consum)

160.30769230769232

In [8]:
# Used std function to find the standard deviation of the per capita daily water consumption

np.std(per_cap_daily_consum)


31.51894330370624

In [9]:
# Question 5D: 

# Used indexing to find the column value of new york city population

nyc_water[:,1]


array([7102100. , 7071639. , 7089241. , 7109105. , 7181224. , 7234514. ,
       7274054. , 7319246. , 7342476. , 7353719. , 7344175. , 7335650. ,
       7374501. , 7428944. , 7506166. , 7570458. , 7633040. , 7697812. ,
       7773443. , 7858259. , 7947660. , 8008278. , 8024963.5, 8041649. ,
       8058334.5, 8075020. , 8091705.5, 8108391. , 8125076.5, 8141762. ,
       8158447.5, 8175133. , 8284098. , 8361179. , 8422460. , 8471990. ,
       8516502. , 8537673. , 8622698. ])

In [12]:
# saved the nyc population column values to nyc_pop

nyc_pop = ([7102100. , 7071639. , 7089241. , 7109105. , 7181224. , 7234514. ,
       7274054. , 7319246. , 7342476. , 7353719. , 7344175. , 7335650. ,
       7374501. , 7428944. , 7506166. , 7570458. , 7633040. , 7697812. ,
       7773443. , 7858259. , 7947660. , 8008278. , 8024963.5, 8041649. ,
       8058334.5, 8075020. , 8091705.5, 8108391. , 8125076.5, 8141762. ,
       8158447.5, 8175133. , 8284098. , 8361179. , 8422460. , 8471990. ,
       8516502. , 8537673. , 8622698. ])

# used np.diff fuction to find the changes in polpulation form year to year in nyc

np.diff(nyc_pop)

pop_diff = np.diff(nyc_pop)

print(pop_diff)



[-30461.   17602.   19864.   72119.   53290.   39540.   45192.   23230.
  11243.   -9544.   -8525.   38851.   54443.   77222.   64292.   62582.
  64772.   75631.   84816.   89401.   60618.   16685.5  16685.5  16685.5
  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5 108965.
  77081.   61281.   49530.   44512.   21171.   85025. ]


In [16]:
# Question 4:

# created an array of total 35 days of cumulative bike ride from NYC to KEY WEST

distance = np.array([55, 120, 150, 175, 175, 215, 250, 280, 320, 375, 425, 485, 485, 535, 590, 640, 685, 725, 770, 810,
                    865, 900, 900, 965, 1005, 1060, 1105, 1140, 1195, 1260, 1300, 1300, 1338.3, 1393.3, 1436.3])

# Used np.diff function to find the each day bike ride (from day 1st to day 35th) of total 35 days bike ride NYC to KEY WEST

np.diff(distance)

diff_arr = np.diff(distance)

all_daily_distance = np.append(distance[0],diff_arr)
print(all_daily_distance)

[55.  65.  30.  25.   0.  40.  35.  30.  40.  55.  50.  60.   0.  50.
 55.  50.  45.  40.  45.  40.  55.  35.   0.  65.  40.  55.  45.  35.
 55.  65.  40.   0.  38.3 55.  43. ]
